apiVersion: v1
kind: ServiceAccount
metadata:
  name: dj-controller
  #namespace: oauther

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dj-controller
rules:
- apiGroups:
  - "dj-kubelet.com"
  resources:
  - tracks
  verbs:
  - list
  - get
  - patch

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - create

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  resourceNames:
  - spotify-oauth

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dj-controller
  #namespace: default
subjects:
- kind: ServiceAccount
  name: dj-controller
  #namespace: oauther
roleRef:
  kind: Role
  name: dj-controller
  apiGroup: rbac.authorization.k8s.io
